version: 5.0.0
variant: default
logo: https://mapp.alicdn.com/1633244893074BvoBzYrEgzOwpbz.png
head:
    favicon: /favicon.ico
    meta:
        - ''
    rss: 
navbar:
    menu:
        主页: /
        分类: /categories
        关于: /about
    links: 
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-gitlab
            url: https://jihulab.com/Tim-Paik/python-tutorial
article:
    highlight:
        theme: atom-one-dark
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: false
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
sidebar:
    left:
        sticky: false
    right:
        sticky: false
plugins:
    animejs: true
    back_to_top: true
    busuanzi: false
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
providers:
    cdn: '[cdnjs]https://lib.baomitu.com/${package}/${version}/${filename}'
    fontcdn: google
    iconcdn: https://lib.baomitu.com/font-awesome/5.15.4/css/all.min.css
